### ISSUE TITLE
Add all prompt keybindings to the configuration

### ISSUE THREAD

**Issue by DougHaber** [DougHaber/lair#7]
## Overview

Keybindings are currently hardcoded.  For example, `ESC-T` to toggle the toolbar is baked right into the code:

```python
@key_bindings.add('escape', 't')
def toggle_toolbar(event):
    ...
```

This change proposes placing all key bindings into the configuration so that they are possible to redefine.

To complete this task:
- All key bindings must be read from the configuration
- The help messages must show the current key bindings
- Documentation must be updated

**Comment by DougHaber** [comment]
Key bindings are now in the configuration:

```yaml
chat.keys.session.new: 'c-x n'
chat.keys.session.next: 'c-x space'
chat.keys.session.previous: 'c-x p'
chat.keys.session.reset: 'c-x r'
chat.keys.session.show: 'c-x s'
chat.keys.session.switch: 'c-x c-x'
chat.keys.session.set_alias: 'c-x c-a'
chat.keys.session.set_title: 'c-x c-t'
chat.keys.show_help: 'c-x ?'
chat.keys.list_models: 'c-x m'
chat.keys.list_tools: 'c-x t'
chat.keys.toggle_debug: 'escape d'
chat.keys.toggle_markdown: 'escape m'
chat.keys.toggle_multiline_input: 'escape l'
chat.keys.toggle_toolbar: 'escape b'
chat.keys.toggle_tools: 'escape t'
chat.keys.toggle_verbose: 'escape v'
chat.keys.toggle_word_wrap: 'escape w'
```

I do like the idea of making a chat.keys list based structure` instead of individual items where each action has a name.  That would make it possible to assign multiple keys to the same action.

This next release is getting a bit big, so I'm going to hold off on that for now.
